services:
  verification:
    image: node:20.11.1
    mem_limit: 1536m
    memswap_limit: 1536m
    command: node /verification/server.js
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./:/verification
      - ./solc-repo/bin:/verification/solc-repo/bin
      - ./solc-repo/js:/verification/solc-repo/js
    env_file:
      - path: .env
    healthcheck:
      test: [ "CMD-SHELL", "free -m | awk '/Mem:/ {exit ($3 > 1500 ? 1 : 0)}'" ]
      interval: 10s
      retries: 3
      start_period: 30s
